export const sentencesBank = [
    "All humans are mortal beings who eventually experience the end of life.",
    "If rain occurs, the ground becomes wet due to the water falling from the sky.",
    "Every even number is divisible by 2, having no remainder when divided.",
    "Birds possess the ability to fly through the air using their wings for propulsion.",
    "Studying hard increases the likelihood of achieving good grades in academic pursuits.",
    "No cats belong to the reptile category; they are separate species with distinct characteristics.",
    "Triangles consist of three straight sides that connect to form closed geometric figures.",
    "Shapes having four equal sides can be identified as squares in Euclidean geometry.",
    "Mammals exhibit the presence of hair or fur as a common characteristic within the class.",
    "On weekdays, people generally engage in work-related activities as part of their routine.",
    "The sun's daily movement creates the perception of it rising in the eastern part of the sky.",
    "All apples are fruits, categorized as edible reproductive structures of flowering plants.",
    "Animals possessing gills can respire underwater by extracting oxygen from the surrounding water.",
    "No reptiles give birth to live young; instead, they lay eggs for reproduction.",
    "A number divisible by 3 is also divisible by 6, having a common factor of 2.",
    "Planets revolve around the sun in elliptical orbits, following the principles of celestial mechanics.",
    "An equilateral triangle possesses three congruent sides, ensuring all angles are of equal measure.",
    "Dogs, as members of the Canidae family, lack the ability to produce meowing sounds like cats.",
    "Roses, known for their attractive blossoms, fall into the category of flowering plants.",
    "Putting in the effort through dedicated studying generally leads to positive academic outcomes.",
    "Mammals, including humans and many other animals, give birth to live offspring instead of laying eggs.",
    "In Euclidean geometry, squares represent quadrilateral shapes with all sides of equal length.",
    "During the winter season, snowfall becomes a common occurrence due to lower temperatures.",
    "Prime numbers, except for 1, have no divisors other than 1 and themselves, making them unique.",
    "Birds and mammals belong to distinct taxonomic groups and possess different characteristics.",
    "When heat is applied to water, it reaches its boiling point and turns into vapor or steam.",
    "Right angles, measuring 90 degrees, are an essential concept in Euclidean geometry.",
    "Feathers serve as a distinguishing feature of birds, allowing them to achieve flight.",
    "Vegetables and animals belong to separate kingdoms in biological classification.",
    "Fish, as aquatic vertebrates, live in water bodies such as oceans, rivers, and lakes.",
    "During nighttime, the absence of sunlight creates a dark environment in the outdoor surroundings.",
    "Whole numbers, including positive integers and zero, comprise a subset of the real number system.",
    "Snakes lack limbs, making them classified as legless reptiles with elongated bodies.",
    "Combining blue and yellow pigments results in the creation of the color green.",
    "The sum of angles in any triangle always equals 180 degrees, a fundamental geometric principle.",
    "Objects near the Earth's surface experience gravitational attraction, leading to downward motion.",
    "Insects, characterized by their exoskeleton and segmented bodies, do not possess internal skeletons.",
    "Dogs, members of the Canidae family, belong to the class of mammals with diverse breeds.",
    "Lack of sufficient sleep results in feelings of fatigue and decreased mental and physical performance.",
    "Rectangles consist of four sides, with opposite sides being equal in length and four right angles.",
    "Elephants, large land mammals known for their distinctive features, are incapable of flying.",
    "The summer season is generally associated with high temperatures and warm weather conditions.",
    "Spiders, belonging to the arachnid class, typically possess eight legs and multiple eyes.",
    "A number divisible by both 2 and 3 is also divisible by 6, having these two factors in common.",
    "Roses, admired for their beauty and fragrance, fall within the category of flowering plants.",
    "Water is an essential requirement for the survival of all living organisms on Earth.",
    "Multiplying two negative numbers results in a positive product, a rule of arithmetic.",
    "Mammals, a diverse class of animals, share the characteristic of possessing a backbone or vertebral column.",
    "Birds possess unique vocalizations but are incapable of producing barking sounds like dogs.",
    "If it rains, the ground becomes wet due to the precipitation descending from the atmosphere.",
    "Squares are a specific type of quadrilateral with four sides of equal length and four right angles.",
    "Transparency refers to the property of allowing light to pass through an object without significant obstruction.",
    "Fish, as aquatic creatures, lack the physiological adaptations required for survival on land.",
    "Trees, prominent members of the plant kingdom, possess root structures for anchoring and nutrient absorption.",
    "Division of any number by zero results in an undefined value, as it violates mathematical principles.",
    "Cars, vehicles designed for land transportation, lack the necessary adaptations for swimming in water.",
    "Prime numbers, except for 2, are always odd, lacking divisibility by even numbers other than 2.",
    "Sunny weather implies the absence of rainfall, presenting a dry and bright atmospheric condition.",
    "Mammals, including humans, give birth to live offspring, nourishing them through internal gestation.",
    "Quadrilaterals, shapes with four sides, include squares, rectangles, parallelograms, and trapezoids.",
    "Snakes, elongated reptiles without limbs, utilize their bodies to move across various surfaces.",
    "Birds, characterized by feathers and beaks, reproduce by laying eggs for their offspring's development.",
    "Adding two odd numbers always results in an even sum, a property of arithmetic operations.",
    "Circles and squares represent distinct geometric shapes, with no overlapping characteristics.",
    "Oranges, citrus fruits known for their tangy taste, belong to the broader category of fruits.",
    "Cold temperatures necessitate the use of warm clothing to maintain comfort and avoid chilling effects.",
    "Equilateral triangles, possessing three equal sides, also fall within the category of isosceles triangles.",
    "Spiders, arthropods belonging to the class Arachnida, differ from insects in terms of body structure.",
    "Butterflies undergo metamorphosis, transitioning through distinct life stages from eggs to caterpillars and finally adults.",
    "Every living organism requires oxygen to carry out cellular respiration.",
    "If you exercise regularly, your physical fitness and endurance levels will improve.",
    "No squares can have a curved side; they are characterized by straight edges.",
    "All mammals possess mammary glands used for milk production to nourish their young.",
    "If you sow seeds and provide adequate water and sunlight, plants will grow.",
    "No fish possess lungs; they respire through gills, extracting oxygen from water.",
    "All right-angled triangles exhibit the Pythagorean theorem, relating side lengths.",
    "If it is dark outside, it indicates the absence of sufficient light or illumination.",
    "Every action has an equal and opposite reaction, as described by Newton's third law.",
    "No bacteria are visible to the naked eye; they require a microscope for observation.",
    "All fruits contain seeds, serving as a means of plant reproduction and dispersal.",
    "If you invest in a diversified portfolio, it helps reduce investment risk.",
    "No human beings have wings; they lack the anatomical structures for flight.",
    "All mammals possess a neocortex, contributing to advanced cognitive abilities.",
    "If an object is denser than the fluid it is immersed in, it will sink.",
    "Every natural number greater than 1 can be expressed as a product of prime factors.",
    "No reptiles can regulate their body temperature internally; they rely on external sources.",
    "All planets in our solar system orbit the sun in elliptical paths called orbits.",
    "If you apply force to an object, it accelerates according to Newton's second law of motion.",
    "No insects possess a backbone or vertebral column; they are invertebrate organisms.",
    "All birds have beaks that serve various functions, including feeding and grooming.",
    "If you mix red and blue pigments, you get purple as a result of color blending.",
    "No rectangles have diagonals of equal length; they exhibit distinct diagonal measurements.",
    "All mammals possess a four-chambered heart, facilitating efficient blood circulation.",
    "If you travel eastward around the globe, you eventually return to your starting point.",
    "No non-metals conduct electricity; they are generally poor electrical conductors.",
    "All spiders produce silk, using it for various purposes like building webs and capturing prey.",
    "If you eat a balanced diet and exercise, you can maintain a healthy body weight.",
    "No mammals can photosynthesize; they obtain energy through other means, such as eating.",
    "All matter consists of atoms, which are the fundamental building blocks of the universe.",
    "If you expose metal to high temperatures, it expands due to thermal expansion.",
    "No squares can have diagonals perpendicular to each other; they are non-rectangular.",
    "All living organisms experience growth and development throughout their lifespan.",
    "If you mix yellow and red pigments, you get orange as a result of color mixing.",
    "No spiders possess wings; they rely on other means of locomotion, such as crawling.",
    "All organisms exhibit genetic diversity, which contributes to species adaptation and survival.",
    "If you increase the concentration of a solute, it raises the osmotic pressure of a solution.",
    "No sound can travel through a vacuum, as it requires a medium for transmission.",
    "All mammals have a backbone or vertebral column, distinguishing them from other animal groups.",
    "If you expose ice to higher temperatures, it melts and transforms into liquid water.",
    "No birds have teeth; they possess beaks that are adapted for various feeding strategies.",
    "All chemical reactions involve the rearrangement of atoms to form new substances.",
    "If you decrease the temperature of a gas, its volume tends to decrease as well.",
    "No rectangles have all sides of equal length; those are specific to squares.",
    "All mammals possess hair or fur, which serves various functions like insulation and protection.",
    "If you apply a force to an object and keep it at rest, it experiences static friction.",
    "No triangles have four sides; they are polygons with exactly three straight sides.",
    "All living organisms are composed of cells, which are the basic units of life.",
    "If you mix yellow and blue pigments, you get green as a result of color combination.",
    "No reptiles possess feathers; they are unique to birds and certain dinosaur species.",
    "All chemical elements are composed of atoms, which have distinct properties and characteristics.",
    "If you provide plants with adequate light, they undergo photosynthesis to produce energy.",
    "No mammals lay eggs; instead, they give birth to live offspring through internal gestation."
];