export const sentencesBank = [
    "All humans are mortal beings who eventually experience the end of life.",
    "If rain occurs, the ground becomes wet due to the water falling from the sky.",
    "Every even number is divisible by 2, having no remainder when divided.",
    "Birds possess the ability to fly through the air using their wings for propulsion.",
    "Studying hard increases the likelihood of achieving good grades in academic pursuits.",
    "No cats belong to the reptile category; they are separate species with distinct characteristics.",
    "Triangles consist of three straight sides that connect to form closed geometric figures.",
    "Shapes having four equal sides can be identified as squares in Euclidean geometry.",
    "Mammals exhibit the presence of hair or fur as a common characteristic within the class.",
    "On weekdays, people generally engage in work-related activities as part of their routine.",
    "The sun's daily movement creates the perception of it rising in the eastern part of the sky.",
    "All apples are fruits, categorized as edible reproductive structures of flowering plants.",
    "Animals possessing gills can respire underwater by extracting oxygen from the surrounding water.",
    "No reptiles give birth to live young; instead, they lay eggs for reproduction.",
    "A number divisible by 3 is also divisible by 6, having a common factor of 2.",
    "Planets revolve around the sun in elliptical orbits, following the principles of celestial mechanics.",
    "An equilateral triangle possesses three congruent sides, ensuring all angles are of equal measure.",
    "Dogs, as members of the Canidae family, lack the ability to produce meowing sounds like cats.",
    "Roses, known for their attractive blossoms, fall into the category of flowering plants.",
    "Putting in the effort through dedicated studying generally leads to positive academic outcomes.",
    "Mammals, including humans and many other animals, give birth to live offspring instead of laying eggs.",
    "In Euclidean geometry, squares represent quadrilateral shapes with all sides of equal length.",
    "During the winter season, snowfall becomes a common occurrence due to lower temperatures.",
    "Prime numbers, except for 1, have no divisors other than 1 and themselves, making them unique.",
    "Birds and mammals belong to distinct taxonomic groups and possess different characteristics.",
    "When heat is applied to water, it reaches its boiling point and turns into vapor or steam.",
    "Right angles, measuring 90 degrees, are an essential concept in Euclidean geometry.",
    "Feathers serve as a distinguishing feature of birds, allowing them to achieve flight.",
    "Vegetables and animals belong to separate kingdoms in biological classification.",
    "Fish, as aquatic vertebrates, live in water bodies such as oceans, rivers, and lakes.",
    "During nighttime, the absence of sunlight creates a dark environment in the outdoor surroundings.",
    "Whole numbers, including positive integers and zero, comprise a subset of the real number system.",
    "Snakes lack limbs, making them classified as legless reptiles with elongated bodies.",
    "Combining blue and yellow pigments results in the creation of the color green.",
    "The sum of angles in any triangle always equals 180 degrees, a fundamental geometric principle.",
    "Objects near the Earth's surface experience gravitational attraction, leading to downward motion.",
    "Insects, characterized by their exoskeleton and segmented bodies, do not possess internal skeletons.",
    "Dogs, members of the Canidae family, belong to the class of mammals with diverse breeds.",
    "Lack of sufficient sleep results in feelings of fatigue and decreased mental and physical performance.",
    "Rectangles consist of four sides, with opposite sides being equal in length and four right angles.",
    "Elephants, large land mammals known for their distinctive features, are incapable of flying.",
    "The summer season is generally associated with high temperatures and warm weather conditions.",
    "Spiders, belonging to the arachnid class, typically possess eight legs and multiple eyes.",
    "A number divisible by both 2 and 3 is also divisible by 6, having these two factors in common.",
    "Roses, admired for their beauty and fragrance, fall within the category of flowering plants.",
    "Water is an essential requirement for the survival of all living organisms on Earth.",
    "Multiplying two negative numbers results in a positive product, a rule of arithmetic.",
    "Mammals, a diverse class of animals, share the characteristic of possessing a backbone or vertebral column.",
    "Birds possess unique vocalizations but are incapable of producing barking sounds like dogs.",
    "If it rains, the ground becomes wet due to the precipitation descending from the atmosphere.",
    "Squares are a specific type of quadrilateral with four sides of equal length and four right angles.",
    "Transparency refers to the property of allowing light to pass through an object without significant obstruction.",
    "Fish, as aquatic creatures, lack the physiological adaptations required for survival on land.",
    "Trees, prominent members of the plant kingdom, possess root structures for anchoring and nutrient absorption.",
    "Division of any number by zero results in an undefined value, as it violates mathematical principles.",
    "Cars, vehicles designed for land transportation, lack the necessary adaptations for swimming in water.",
    "Prime numbers, except for 2, are always odd, lacking divisibility by even numbers other than 2.",
    "Sunny weather implies the absence of rainfall, presenting a dry and bright atmospheric condition.",
    "Mammals, including humans, give birth to live offspring, nourishing them through internal gestation.",
    "Quadrilaterals, shapes with four sides, include squares, rectangles, parallelograms, and trapezoids.",
    "Snakes, elongated reptiles without limbs, utilize their bodies to move across various surfaces.",
    "Birds, characterized by feathers and beaks, reproduce by laying eggs for their offspring's development.",
    "Adding two odd numbers always results in an even sum, a property of arithmetic operations.",
    "Circles and squares represent distinct geometric shapes, with no overlapping characteristics.",
    "Oranges, citrus fruits known for their tangy taste, belong to the broader category of fruits.",
    "Cold temperatures necessitate the use of warm clothing to maintain comfort and avoid chilling effects.",
    "Equilateral triangles, possessing three equal sides, also fall within the category of isosceles triangles.",
    "Spiders, arthropods belonging to the class Arachnida, differ from insects in terms of body structure.",
    "Butterflies undergo metamorphosis, transitioning through distinct life stages from eggs to caterpillars and finally adults.",
    "Every living organism requires oxygen to carry out cellular respiration.",
    "If you exercise regularly, your physical fitness and endurance levels will improve.",
    "No squares can have a curved side; they are characterized by straight edges.",
    "All mammals possess mammary glands used for milk production to nourish their young.",
    "If you sow seeds and provide adequate water and sunlight, plants will grow.",
    "No fish possess lungs; they respire through gills, extracting oxygen from water.",
    "All right-angled triangles exhibit the Pythagorean theorem, relating side lengths.",
    "If it is dark outside, it indicates the absence of sufficient light or illumination.",
    "Every action has an equal and opposite reaction, as described by Newton's third law.",
    "No bacteria are visible to the naked eye; they require a microscope for observation.",
    "All fruits contain seeds, serving as a means of plant reproduction and dispersal.",
    "If you invest in a diversified portfolio, it helps reduce investment risk.",
    "No human beings have wings; they lack the anatomical structures for flight.",
    "All mammals possess a neocortex, contributing to advanced cognitive abilities.",
    "If an object is denser than the fluid it is immersed in, it will sink.",
    "Every natural number greater than 1 can be expressed as a product of prime factors.",
    "No reptiles can regulate their body temperature internally; they rely on external sources.",
    "All planets in our solar system orbit the sun in elliptical paths called orbits.",
    "If you apply force to an object, it accelerates according to Newton's second law of motion.",
    "No insects possess a backbone or vertebral column; they are invertebrate organisms.",
    "All birds have beaks that serve various functions, including feeding and grooming.",
    "If you mix red and blue pigments, you get purple as a result of color blending.",
    "No rectangles have diagonals of equal length; they exhibit distinct diagonal measurements.",
    "All mammals possess a four-chambered heart, facilitating efficient blood circulation.",
    "If you travel eastward around the globe, you eventually return to your starting point.",
    "No non-metals conduct electricity; they are generally poor electrical conductors.",
    "All spiders produce silk, using it for various purposes like building webs and capturing prey.",
    "If you eat a balanced diet and exercise, you can maintain a healthy body weight.",
    "No mammals can photosynthesize; they obtain energy through other means, such as eating.",
    "All matter consists of atoms, which are the fundamental building blocks of the universe.",
    "If you expose metal to high temperatures, it expands due to thermal expansion.",
    "No squares can have diagonals perpendicular to each other; they are non-rectangular.",
    "All living organisms experience growth and development throughout their lifespan.",
    "If you mix yellow and red pigments, you get orange as a result of color mixing.",
    "No spiders possess wings; they rely on other means of locomotion, such as crawling.",
    "All organisms exhibit genetic diversity, which contributes to species adaptation and survival.",
    "If you increase the concentration of a solute, it raises the osmotic pressure of a solution.",
    "No sound can travel through a vacuum, as it requires a medium for transmission.",
    "All mammals have a backbone or vertebral column, distinguishing them from other animal groups.",
    "If you expose ice to higher temperatures, it melts and transforms into liquid water.",
    "No birds have teeth; they possess beaks that are adapted for various feeding strategies.",
    "All chemical reactions involve the rearrangement of atoms to form new substances.",
    "If you decrease the temperature of a gas, its volume tends to decrease as well.",
    "No rectangles have all sides of equal length; those are specific to squares.",
    "All mammals possess hair or fur, which serves various functions like insulation and protection.",
    "If you apply a force to an object and keep it at rest, it experiences static friction.",
    "No triangles have four sides; they are polygons with exactly three straight sides.",
    "All living organisms are composed of cells, which are the basic units of life.",
    "If you mix yellow and blue pigments, you get green as a result of color combination.",
    "No reptiles possess feathers; they are unique to birds and certain dinosaur species.",
    "All chemical elements are composed of atoms, which have distinct properties and characteristics.",
    "If you provide plants with adequate light, they undergo photosynthesis to produce energy.",
    "No mammals lay eggs; instead, they give birth to live offspring through internal gestation.",
    "Formula 1 is a premier motorsport racing series that captivates fans worldwide.",
    "Lewis Hamilton is a seven-time Formula 1 World Champion, cementing his status as one of the sport's greatest drivers.",
    "Mercedes-AMG Petronas Formula One Team is a dominant force in F1, securing multiple championships in recent years.",
    "Max Verstappen is a rising star in Formula 1, showcasing exceptional talent and challenging the established order.",
    "Red Bull Racing is a formidable team in Formula 1, known for its aggressive approach and innovative strategies.",
    "The Monaco Grand Prix is one of the most iconic races on the Formula 1 calendar, renowned for its glamour and challenging street circuit.",
    "Silverstone Circuit in the United Kingdom is a historic venue that hosts the British Grand Prix, a highlight of the F1 season.",
    "The Italian Grand Prix at Monza is a high-speed spectacle that attracts passionate fans and delivers thrilling racing action.",
    "Fernando Alonso, a two-time Formula 1 World Champion, returned to the sport with the Alpine F1 Team after a brief hiatus.",
    "Scuderia Ferrari, the oldest and most successful team in Formula 1 history, boasts a massive fan following and a rich heritage.",
    "Suzuka Circuit in Japan is a beloved track among drivers and fans, renowned for its unique figure-eight layout.",
    "Michael Schumacher, a seven-time Formula 1 World Champion, holds numerous records and is considered a legend of the sport.",
    "Monza Circuit in Italy is famous for its long straights and fast corners, providing an exhilarating experience for drivers.",
    "Ayrton Senna, regarded as one of the greatest drivers in Formula 1 history, left an indelible mark on the sport before his untimely death.",
    "Circuit de Spa-Francorchamps in Belgium is a favorite among drivers, featuring challenging elevation changes and unpredictable weather.",
    "McLaren Racing, a renowned Formula 1 team, has a rich history and has produced numerous championship-winning cars.",
    "The Singapore Grand Prix is a night race held on the Marina Bay Street Circuit, offering a unique spectacle for fans.",
    "Nico Rosberg, the 2016 Formula 1 World Champion, achieved his childhood dream before retiring from the sport.",
    "Albert Park Circuit in Melbourne, Australia, hosts the season-opening Australian Grand Prix, setting the stage for the F1 championship.",
    "Daniel Ricciardo, an Australian driver known for his infectious personality, currently races for McLaren in Formula 1.",
    "Circuit of the Americas in Austin, Texas, is a state-of-the-art facility that hosts the United States Grand Prix.",
    "The Japanese Grand Prix at Suzuka has witnessed iconic moments in Formula 1 history, with drivers showcasing their skills on this challenging track.",
    "Nürburgring in Germany is famous for its Nordschleife circuit, known as the 'Green Hell,' and has hosted many legendary races.",
    "Valtteri Bottas, a Finnish driver, partners with Lewis Hamilton at Mercedes-AMG Petronas Formula One Team.",
    "Bahrain International Circuit hosts the season-opening race in the Middle East, providing a thrilling start to the Formula 1 calendar.",
    "Sebastian Vettel, a four-time Formula 1 World Champion, joined Aston Martin Cognizant Formula One Team in his quest for further success.",
    "Interlagos Circuit in São Paulo, Brazil, has a passionate fan base and has witnessed dramatic races throughout its history.",
    "Esteban Ocon, a young French driver, represents Alpine F1 Team in Formula 1, showcasing his talent and potential.",
    "Circuit de Barcelona-Catalunya in Spain is a popular testing venue for Formula 1 teams to prepare for the season ahead.",
    "Williams Racing, a historic Formula 1 team, has seen its fortunes decline in recent years but continues to compete with determination.",
    "Sergio Perez, a Mexican driver known for his tire management skills, currently races for Red Bull Racing.",
    "Paul Ricard Circuit in France features distinctive blue and red runoff areas and hosts the French Grand Prix.",
    "Jenson Button, the 2009 Formula 1 World Champion, enjoyed a successful career with various teams before retiring from the sport.",
    "Imola Circuit in Italy is known for its challenging layout and has returned to the Formula 1 calendar in recent years.",
    "Alfa Romeo Racing ORLEN, with its rich racing heritage, competes in Formula 1 with an iconic Italian brand.",
    "Gulf Air Bahrain Grand Prix is a night race held at Bahrain International Circuit, providing a unique atmosphere for spectators.",
    "Antonio Giovinazzi, an Italian driver, represents Alfa Romeo Racing ORLEN in Formula 1, aiming to achieve consistent results.",
    "Haas F1 Team, an American outfit, entered Formula 1 in 2016 and has since been a part of the competitive grid.",
    "Portimão Circuit in Portugal is a challenging track with multiple elevation changes, hosting the Portuguese Grand Prix.",
    "Mick Schumacher, son of Michael Schumacher, made his Formula 1 debut in 2021 with Haas F1 Team.",
    "Nikita Mazepin, a Russian driver, partnered with Mick Schumacher at Haas F1 Team for the 2021 Formula 1 season.",
    "Yas Marina Circuit in Abu Dhabi hosts the season-ending Abu Dhabi Grand Prix, often deciding the championship outcome.",
    "Lando Norris, a young British driver, impresses in Formula 1 with McLaren Racing, showcasing his raw talent and potential.",
    "Imola Circuit holds a special place in Formula 1 history, having hosted numerous memorable races over the years.",
    "F1 cars are the pinnacle of motorsport engineering, with cutting-edge technology and aerodynamic designs.",
    "The French Grand Prix has a rich heritage, with its origins dating back to the early days of Formula 1.",
    "AlphaTauri, the sister team of Red Bull Racing, competes in Formula 1 with a focus on developing young talent.",
    "F1 teams invest significant resources in research and development, pushing the boundaries of performance and innovation.",
    "The Mexican Grand Prix at Autódromo Hermanos Rodríguez in Mexico City is a vibrant and festive race on the F1 calendar.",
    "McLaren has a storied history in Formula 1, having won multiple championships with legendary drivers.",
    "F1 races feature intense battles for position, with drivers showcasing their skills and strategic prowess.",
    "F1 engineers play a crucial role in optimizing the performance and reliability of the cars, working tirelessly behind the scenes.",
    "The Australian Grand Prix in Melbourne marks the beginning of the Formula 1 season, generating excitement and anticipation.",
    "The Canadian Grand Prix at Circuit Gilles Villeneuve in Montreal is a popular race among fans and drivers.",
    "F1 drivers undergo rigorous physical training to withstand the demands of racing at high speeds for extended periods.",
    "The Russian Grand Prix at Sochi Autodrom provides a unique blend of street and circuit elements, challenging drivers and teams.",
    "The United States Grand Prix at Circuit of the Americas attracts a diverse and enthusiastic crowd, celebrating the sport's popularity.",
    "F1 pit stops are a ballet of precision and speed, showcasing the teamwork and coordination of the pit crew.",
    "The Spanish Grand Prix at Circuit de Barcelona-Catalunya is a crucial race for teams to assess their car's performance and make improvements.",
    "F1 fans travel from around the world to attend races, creating a vibrant and international atmosphere at each Grand Prix.",
    "The Belgian Grand Prix at Circuit de Spa-Francorchamps is notorious for unpredictable weather conditions, adding an element of challenge and excitement.",
    "F1 sponsors and partnerships play a vital role in supporting teams and drivers, contributing to the financial sustainability of the sport.",
    "The Austrian Grand Prix at Red Bull Ring is a favorite among drivers, offering a picturesque setting and exhilarating racing.",
    "F1 regulations undergo periodic updates to maintain competitiveness, ensure safety, and promote fair competition among teams.",
    "The Emilia Romagna Grand Prix at Imola Circuit provides a unique test for drivers, with its tight and technical layout.",
    "F1 drivers have to strike a balance between aggression and precision, pushing the limits while avoiding unnecessary risks.",
    "The Brazilian Grand Prix at Interlagos Circuit has a rich history, often producing unpredictable races and dramatic moments.",
    "F1 journalists and media provide extensive coverage and analysis of races, keeping fans informed about the latest developments.",
    "The Dutch Grand Prix returned to the F1 calendar in 2021, with Zandvoort Circuit hosting the highly anticipated race.",
    "F1 teams employ strategists who analyze data and make critical decisions during races to optimize their chances of success.",
    "The Saudi Arabian Grand Prix made its debut in 2021, featuring a night race on the Jeddah Street Circuit.",
    "F1 circuits span the globe, showcasing the sport's international appeal and attracting fans from diverse backgrounds.",
    "The Azerbaijan Grand Prix in Baku is known for its tight and twisty street circuit, providing exciting racing and unpredictable outcomes.",
    "F1 drivers compete not only for individual glory but also for their teams, contributing to the Constructors' Championship.",
    "The Hungarian Grand Prix at Hungaroring offers a challenging and technical track, testing drivers' skills and concentration.",
    "F1 safety measures and innovations continue to evolve, prioritizing the well-being of drivers and improving overall race conditions.",
    "The Styrian Grand Prix, held at Red Bull Ring, adds an additional race to the Formula 1 calendar, delighting fans with more action.",
    "F1 cars can reach speeds of over 200 miles per hour, delivering exhilarating racing and heart-stopping overtakes.",
    "The Turkish Grand Prix at Istanbul Park is known for its demanding layout and changing track conditions, providing a unique test for drivers.",
    "F1 fan festivals and events allow enthusiasts to engage with the sport, meet drivers, and experience the excitement firsthand.",
    "The Saudi Arabian Grand Prix features a stunning night race under the lights, showcasing the glamour and spectacle of Formula 1.",
    "F1 rivalries add drama and intensity to the sport, with fierce battles on and off the track between drivers and teams.",
    "The Australian Grand Prix has a rich history, with iconic moments and legendary drivers leaving their mark on the race.",
    "F1 cars utilize hybrid power units, combining internal combustion engines with electric motor technology for enhanced performance and efficiency.",
    "The Japanese Grand Prix at Suzuka has a unique figure-eight layout, challenging drivers with its technical corners and fast-paced sections.",
    "F1 hospitality areas and paddocks provide a luxurious experience for VIP guests and team members, offering exclusivity and comfort.",
    "The Mexican Grand Prix boasts a festive atmosphere, with passionate fans cheering for their favorite drivers and teams.",
    "F1 teams employ aerodynamicists to optimize the car's aerodynamics, enhancing performance and maximizing downforce.",
    "The French Grand Prix returned to Circuit Paul Ricard in 2018, rekindling its historic legacy in Formula 1.",
    "F1 race weekends consist of practice sessions, qualifying rounds, and the main race, providing multiple opportunities for teams to fine-tune their performance.",
    "The United States Grand Prix showcases the growing popularity of Formula 1 in North America, attracting a diverse and enthusiastic fan base.",
    "F1 engineers constantly explore new materials and technologies to improve car performance, seeking every possible advantage on the track.",
    "The Singapore Grand Prix is a visually spectacular night race, with the cityscape serving as a breathtaking backdrop to the F1 action.",
    "F1 drivers' helmets are personalized and often reflect their personality, sponsors, and team colors, becoming iconic symbols of their identity.",
    "The Hungarian Grand Prix has witnessed thrilling races and unexpected outcomes, with its tight and twisty layout providing ample opportunities for overtaking.",
    "F1 telemetry systems gather real-time data from the car, helping teams analyze performance, optimize strategy, and make informed decisions.",
    "The Bahrain Grand Prix at Bahrain International Circuit has become a staple on the Formula 1 calendar, known for its thrilling night race.",
    "F1 teams invest in wind tunnel testing and computational fluid dynamics to optimize the car's aerodynamics and reduce drag.",
    "The British Grand Prix at Silverstone Circuit is steeped in history and tradition, attracting massive crowds and passionate support.",
    "F1 drivers participate in rigorous fitness training, focusing on strength, endurance, and reflexes to withstand the physical demands of racing.",
    "The Mexican Grand Prix features the iconic Peraltada corner at Autódromo Hermanos Rodríguez, testing drivers' bravery and car control.",
    "F1 media coverage extends beyond television, with live streaming, social media updates, and interactive platforms providing fans with instant access to the action.",
    "The Canadian Grand Prix is known for its challenging Circuit Gilles Villeneuve, requiring precision and bravery from the drivers.",
    "F1 teams conduct pre-season testing to evaluate their car's performance, gather data, and identify areas for improvement.",
    "The Russian Grand Prix at Sochi Autodrom offers a unique blend of street and permanent circuit sections, creating an intriguing race.",
    "F1 tire management is crucial, with drivers and teams carefully monitoring tire wear and degradation throughout a race.",
    "The Spanish Grand Prix is a pivotal race for teams to assess their car's development and make adjustments for the remainder of the season.",
    "F1 regulations govern various aspects of the sport, including car design, engine specifications, and sporting conduct, ensuring fair competition.",
    "The Dutch Grand Prix's return to Zandvoort Circuit reignites the passion of Dutch fans, creating a sea of orange in the grandstands.",
    "F1 drivers engage in media interviews and press conferences, providing insights into their performance, strategy, and personal experiences.",
    "The Australian Grand Prix's Melbourne Park circuit combines a mix of fast and technical sections, offering a challenging race for drivers.",
    "F1 safety cars play a crucial role in managing on-track incidents, ensuring the safety of drivers and marshals during races.",
    "The Portuguese Grand Prix returned to the F1 calendar in 2020, with Portimão Circuit providing a thrilling challenge for the drivers.",
    "F1 fans engage in spirited debates and discussions, analyzing race performances, driver rivalries, and team strategies."
];